services:
  postgres:
    image: postgres:15
    container_name: notification_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

  app:
    build: .
    container_name: notification_app
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres@postgres:5432/notifications?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata:

